# hostname (and path) to the root
baseURL: "https://www.markdriscoll.xyz"

# Customer parameters
params:
  description: "A starter repo for Hugo"
  rssURL:
    main: "https://gomakethings.com/feed/index.xml"
  rssLimit: 7

# Caches
caches:
  getjson:
    maxAge: "5m"

# The language code for the site
languageCode: "en-us"

# Site title
title: "mark driscoll"

# theme to use (located by default in /themes/THEMENAME/)
theme: "scratch"

# Permalinks
# See "content-management/permalinks"
permalinks:
  articles: /:title/

# Use absolute URLs
canonifyURLs: true

# Allows you to disable all page types and will render nothing related to 'kind';
# values = "page", "home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"
disableKinds: ["page", "home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]

# Files to ignore while rendering
ignoreFiles: []

# the length of text to show in a .Summary
summaryLength: 70

# Pagination
paginate: 35
paginatePath: "page"

# Markdown Options
blackfriday:
  fractions: false

# Syntax Highlighting
pygmentsCodefences: true
pygmentsUseClasses: true